name: LuluPegs
favicon: null
layout_spectrum: 0.9601
typography_spectrum: 0.39976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefef2'
    - '#fd6b7b'
    - '#d5cb74'
    - '#614d00'
  brandStrength: 0.625
  lightness: 0.5794384023174644
  saturation: 0.5625
  rhythmicContrast: 0.8603342017158866
purpose: []
